# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: robotshop
  version: latest
  pullPolicy: IfNotPresent

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# For the mini ones minikube, minishift set to true
nodeport: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

ocCreateRoute: false

######################################
# Affinities for individual workloads
# set in the following way:
# <workload>:
#   affinity: {}
#   nodeSelector: {}
#   tolerations: []
######################################

cart: {}

catalogue: {}

dispatch: {}

mongodb: {}

mysql: {}

payment:
  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  gateway: null
  #gateway: https://www.worldpay.com

rabbitmq: {}

ratings: {}

redis:
  # Storage class to use with redis statefulset.
  storageClassName: standard

shipping: {}

user: {}

web: {}

# Monitoring configuration (optional)
# Enable Loki monitoring with TSDB as default
monitoring:
  enabled: false
  loki:
    # TSDB is the default and preferred index format
    tsdb: true
    enableStructuredMetadata: true
    
    # Grafana dashboard configuration  
    dashboards:
      enabled: false
      prefix: "RobotShop Loki / "
      tags: ["loki", "robotshop", "three-tier"]
    
    # Prometheus alerts
    alerts:
      enabled: false
      
    # Recording rules
    rules:
      enabled: false
